export enum TabOption {
  TRANSCRIPT = 'Transcript',
  CHAT = 'Chat',
  NOTES = 'Notes'
}

export interface Highlight {
  id: string;
  title: string;
  startTime: number; // in seconds
  endTime: number; // in seconds
  color: string; // Hex code
  description?: string;
}

export interface TranscriptSegment {
  id: string;
  text: string;
  timestamp: string;
  startTime: number;
}

export interface VideoData {
  bvid: string;
  title: string;
  author: string;
  category?: string; // New: Video Category (e.g., Tech, Gaming)
  duration: number; // in seconds
  thumbnail: string;
  highlights: Highlight[];
  transcript: TranscriptSegment[];
  isTranscriptSimulated?: boolean; // True if completely hallucinated from metadata
  isAiTranscribed?: boolean; // New: True if generated by AI listening to audio (High Accuracy)
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: number;
}